### ISSUE TITLE
Spike: investigate OpenSDG

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/sprint-planning#35]
[OpenSDG](https://open-sdg.readthedocs.io/en/latest/) is a Python/Ruby library for generating static websites for hosting searchable data, charts, maps etc. The results can be hosted on e.g. GitHub pages.

The underlying data for OpenSDG is CSV along with JSON metadata describing the datasets. However, the data isn't quite "tidy", instead using "indicators" -- a de-normalized column representing a choice of dimension.

This spike is to investigate how we might work with OpenSDG (e.g. via PRs or a fork) to allow the data to be published as Tidy CSV with CSV-W metadata that can be turned directly into RDF Data Cubes. Since the library uses Python to work with the data, we should be able to use `csvwlib` to help create CSV-W.

Questions:
* Can the de-normalized CSV with indicators be turned directly into RDF Data Cubes with CSV2RDF just using the right CSV-W JSON, or would we need to pivot/normalize it first?
* Is there enough information available in the metadata files and indicator files to generate SKOS Concept Schemes via CSV2RDF and a suitable CSV-W JSON?

The output from this spike should include some issues / user stories / features / epics we can use to drive and prioritize any required development.

**Comment by mikeAdamss** [comment]
please see: https://github.com/GSS-Cogs/sdg-build/pull/1
